name:
	Test_Workflow

on:
	push
	
jobs:
	Project Setup:
	runs-on: ubuntu-latest
	steps:
      - uses: actions/checkout@v2
      - name: Build the project  
      - run: make setup
      - run: make start
      - run: make test
      - run: make lint
	
