name:	TestWorkflow

on: 
     - push

jobs:
      Project Setup:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: make setup
      
      Project Run:
      	needs: Project Setup
          run: make start
      
      Project Test:
      	needs: Project Run
      - run: make test
      
      Lint:
      - run: make lint
    
    security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: 3e7d0bc4-471d-4f4c-9050-c47b0ea31aad
